### ISSUE TITLE
Add new logos

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#91]
Needed on:

- [x] Site nav #40 — @alykat 
- [x] Promo images #78 — @alykat 
- [x] Both social screenshotters #89 — @kokonakajima 
- [x] #90 — @kokonakajima 
- [x] Liveblog banner #84 — @alykat 
- [x] Liveblog headlines module #29 — @alykat

**Comment by alykat** [comment]
This is very much not working at small sizes. Asking Marketing for guidance. 

<img width="804" alt="image" src="https://user-images.githubusercontent.com/491318/199391586-410dc161-4ddb-4e6e-b5c6-6131d936d179.png">
